### ISSUE TITLE
Rspec failures

### ISSUE THREAD

**Issue by masukomi** [masukomi/differ#1]
(it was this way when I  found it, I swear )

```

Failures:

  1) Differ::Change should stringify via the current format's #format method
     Failure/Error: Differ::Change.new.to_s
     NoMethodError:
       undefined method `insert' for #<RSpec::Mocks::ArgumentMatchers::AnyArgMatcher:0x007f8da3bea4c8>
     # ./lib/differ/change.rb:27:in `=='
     # ./lib/differ/change.rb:22:in `to_s'
     # ./spec/differ/change_spec.rb:80:in `block (2 levels) in <top (required)>'

  2) Differ::Change (empty) should stringify to ""
     Failure/Error: @change.to_s.should == ''
     NoMethodError:
       undefined method `insert' for #<RSpec::Mocks::ArgumentMatchers::AnyArgMatcher:0x007f8da3bea4c8>
     # ./lib/differ/change.rb:27:in `=='
     # ./lib/differ/change.rb:22:in `to_s'
     # ./spec/differ/change_spec.rb:24:in `block (3 levels) in <top (required)>'

  3) Differ::Diff#to_s should delegate insertion changes to Differ#format
     Failure/Error: @format.should_receive(:call).once.with(i).and_return('!')
     NoMethodError:
       undefined method `insert' for #<RSpec::Mocks::ArgumentMatchers::AnyArgsMatcher:0x007f8da3bea5b8>
     # ./lib/differ/change.rb:27:in `=='
     # ./spec/differ/diff_spec.rb:25:in `block (3 levels) in <top (required)>'

  4) Differ::Diff#format_as should delegate change formatting to the given format
     Failure/Error: @format.should_receive(:call).once.with(@change).and_return('!')
     NoMethodError:
       undefined method `insert' for #<RSpec::Mocks::ArgumentMatchers::AnyArgsMatcher:0x007f8da3bea5b8>
     # ./lib/differ/change.rb:27:in `=='
     # ./spec/differ/diff_spec.rb:40:in `block (3 levels) in <top (required)>'

```
